"A book written by a human."
type Book {
  title: String
  author: String
}

"A human."
type Author {
  name: String
  books: [Book]
}

type Query {
  "Get a list of all books."
  getBooks: [Book]
  "Get a list of all authors."
  getAuthors: [Author]
  "Get an author by full name."
  getAuthorByName(name: String): Author
}

type Mutation {
  "Add a book."
  addBook(title: String, author: String): Book
}
