"A book written by a human."
type Book {
  title: String
  author: Author
}

"A human."
type Author {
  name: String
  books: [Book]
}

type Query {
  authors: [Author]
  author(name: String): Author
  books: [Book]
  book(title: String): [Book]
}

type Mutation {
  "Add a book."
  addBook(title: String, author: String): Book
}

type Subscription {
  bookAdded: Book
}
